# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Text-Identify-BoilerPlate
version:      0.3.1
version_from: lib/Text/Identify/BoilerPlate.pm
installdirs:  site
requires:
    Getopt::Mixed:                 0
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.25
